name = "MultifractalTools"
uuid = "d4a7d00b-0e68-4c54-830d-611b26b28009"
authors = ["NicolauUP <up201805451@up.pt>"]
version = "1.0.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
GLMakie = "0.13.6"
LinearAlgebra = "1.11.0"
LsqFit = "0.15.1"
Statistics = "1.11.1"
julia = "1.11"
Aqua = "0.7"  # Safe range for Aqua
JET = "0.9"   # Safe range for JET
Test = "1"    # Test is a standard library (version 1)

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
