name: Documentation

on:
  push:
    branches:
      - main # Or 'master', whichever is your default branch
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11' # Will use the latest Julia 1.x
      - name: "Cache dependencies"
        uses: julia-actions/cache@v2

      - name: "Install Xvfb for headless plotting"
        uses: GabrielBB/xvfb-action@v1

      - name: "Install dependencies"
        run: julia -e 'using Pkg; Pkg.activate("docs"); Pkg.develop(path=pwd()); Pkg.instantiate()'

        # This step now starts Xvfb AND runs your make.jl script
      - name: "Build and deploy (with Xvfb)"
        uses: GabrielBB/xvfb-action@v1
        with:
          run: julia --project=docs/ docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}